GRID_SIZE = 10
TILE_SIZE = 8
IMAGE_SIZE = GRID_SIZE * TILE_SIZE
MAX_STEPS = 40

FLOOR = 0
WALL = 1
HAZARD = 2
GOAL = 3

ACTION_UP = 0
ACTION_DOWN = 1
ACTION_LEFT = 2
ACTION_RIGHT = 3
ACTION_STAY = 4

NUM_ACTIONS = 5

ACTION_TO_DELTA = {
    ACTION_UP:(-1, 0),
    ACTION_DOWN:(1, 0),
    ACTION_LEFT:(0, -1),
    ACTION_RIGHT:(0, 1),
    ACTION_STAY:(0, 0)
}

ACTION_NAMES = {
    ACTION_UP: "up",
    ACTION_DOWN: "down",
    ACTION_LEFT: "left",
    ACTION_RIGHT: "right",
    ACTION_STAY: "stay"
}